/* CTE Network v23 interface enhancements; preserves existing Sleeper and navigation logic. */
(()=>{
 const paths={home:'M3 10.5 12 3l9 7.5V21h-6v-7H9v7H3z',scores:'M8 3h8l4 4v10l-4 4H8l-4-4V7z M8 3l8 18 M16 3L8 21',standings:'M4 20V11h4v9 M10 20V5h4v15 M16 20v-8h4v8',news:'M4 4h16v16H4z M8 8h8 M8 12h8 M8 16h5',more:'M5 12h.01 M12 12h.01 M19 12h.01',menu:'M4 7h16 M4 12h16 M4 17h16'};
 const icon=(name)=>`<svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.more}"/></svg>`;
 const nav=document.querySelector('.app-bottom-nav');if(nav){nav.querySelectorAll('a,button').forEach((element,i)=>{const mark=element.querySelector('.nav-icon');if(mark)mark.innerHTML=icon(['home','scores','standings','news','more'][i]);if(element.classList.contains('active')&&element.tagName==='A')element.setAttribute('aria-current','page')});}
 const menu=document.getElementById('appHeaderMore');if(menu)menu.innerHTML=icon('menu');
 const sheet=document.querySelector('.app-more-sheet');const backdrop=document.querySelector('.app-more-backdrop');if(sheet&&backdrop){const close=()=>{sheet.classList.remove('open');backdrop.classList.remove('open');document.body.style.overflow='';menu?.setAttribute('aria-expanded','false');document.getElementById('appMoreBtn')?.setAttribute('aria-expanded','false')};[menu,document.getElementById('appMoreBtn')].forEach(button=>button?.addEventListener('click',()=>{const opened=sheet.classList.contains('open');button.setAttribute('aria-expanded',String(opened))}));sheet.querySelectorAll('a').forEach(link=>link.addEventListener('click',close));}
 const strip=document.querySelector('.app-tab-strip');if(strip){const update=()=>{let current=null;strip.querySelectorAll('a').forEach(a=>{if(a.hash&&a.hash===location.hash)current=a});if(current){strip.querySelectorAll('a').forEach(a=>{a.classList.toggle('active',a===current);if(a===current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}};addEventListener('hashchange',update);update();}
})();
