/* CTE Network v23 progressive enhancements; no changes to Sleeper data or routing. */
(()=>{
 const paths={home:'M3 10.5 12 3l9 7.5V21h-6v-7H9v7H3z',scores:'M8 3h8l4 4v10l-4 4H8l-4-4V7z M8 3l8 18 M16 3L8 21',standings:'M4 20V11h4v9 M10 20V5h4v15 M16 20v-8h4v8',news:'M4 4h16v16H4z M8 8h8 M8 12h8 M8 16h5',more:'M5 12h.01 M12 12h.01 M19 12h.01',menu:'M4 7h16 M4 12h16 M4 17h16'};
 const icon=name=>`<svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.more}"/></svg>`;
 const nav=document.querySelector('.app-bottom-nav');if(nav)nav.querySelectorAll('a,button').forEach((el,i)=>{const mark=el.querySelector('.nav-icon');if(mark)mark.innerHTML=icon(['home','scores','standings','news','more'][i]);if(el.classList.contains('active')&&el.tagName==='A')el.setAttribute('aria-current','page')});
 const menu=document.getElementById('appHeaderMore'),more=document.getElementById('appMoreBtn'),sheet=document.querySelector('.app-more-sheet'),back=document.querySelector('.app-more-backdrop');if(menu)menu.innerHTML=icon('menu');
 if(sheet&&back){sheet.id='cteMoreSheet';[menu,more].forEach(b=>{if(!b)return;b.setAttribute('aria-controls',sheet.id);b.setAttribute('aria-expanded',String(sheet.classList.contains('open')))});const sync=()=>{const open=sheet.classList.contains('open');[menu,more].forEach(b=>b?.setAttribute('aria-expanded',String(open)));sheet.setAttribute('aria-hidden',String(!open))};const observer=new MutationObserver(sync);observer.observe(sheet,{attributes:true,attributeFilter:['class']});sync();sheet.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{sheet.classList.remove('open');back.classList.remove('open');document.body.style.overflow=''}));}
 const strip=document.querySelector('.app-tab-strip');if(strip){const update=()=>{const active=[...strip.querySelectorAll('a')].find(a=>a.hash&&a.hash===location.hash);if(active)strip.querySelectorAll('a').forEach(a=>{a.classList.toggle('active',a===active);if(a===active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})};addEventListener('hashchange',update);update()}
 if(location.pathname.endsWith('/scores.html')){const style=document.createElement('style');style.textContent='@media(max-width:820px){#content.league-card{padding:10px!important;background:transparent;border:0;box-shadow:none}#content .matchup{background:#191d22;border:1px solid #343d47;border-radius:14px;padding:15px 12px;margin:0 0 10px;gap:8px}#content .matchup .owner{font-size:14px;line-height:1.25;overflow-wrap:anywhere}#content .matchup .team{font-size:11px;line-height:1.4;overflow-wrap:anywhere}#content .matchup .score{font-size:23px;letter-spacing:-.03em;margin-top:8px;font-variant-numeric:tabular-nums}#content .matchup .vs{font-size:10px;color:#c3a66a}#content .matchup .right{text-align:right}#content .matchup a{text-decoration:none}}';document.head.append(style)}
})();
