(()=>{'use strict';
const view=document.body.dataset.view;if(!view)return;
const $=id=>document.getElementById(id),esc=CTE_UI.esc,fmt=CTE_UI.fmt;
const stories=[...(window.CTE_NEWS||[])].sort((a,b)=>b.date.localeCompare(a.date));
const date=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'});
const href=s=>'article.html?id='+encodeURIComponent(s.id);
const picture=s=>/anita|holly/i.test(s.author||s.title)?'anita-headcheck.webp':/carl|scaries/i.test((s.author||'')+' '+s.title)?'concussion-carl.webp':null;
const shortTitle=s=>s.title.replace(/^ANITA ON THE SIDELINE:\s*/i,'').replace(/^CARL'S RECEIPTS:\s*/i,'');
const cover=s=>`<a href="${href(s)}" class="n-cover-link ${picture(s)?'':'n-cover-text'}"><div class="n-cover-art ${picture(s)?.includes('carl')?'is-carl':''}"><span class="n-cover-watermark" aria-hidden="true">CTE</span>${picture(s)?`<img src="${picture(s)}" alt="${esc(s.author||'CTE Network analyst')}" fetchpriority="high">`:''}</div><div class="n-cover-copy"><span class="n-cover-category">${esc(s.category)} <i></i> ${date(s.date)}</span><h2>${esc(shortTitle(s))}</h2><p>${esc(s.excerpt)}</p><div class="n-cover-bottom"><span>${esc(s.author||'CTE Network')}</span><span class="n-cover-cta">Read story <b>↗</b></span></div></div></a>`;
const storyRow=(s,i)=>`<a class="n-story-row" href="${href(s)}"><span class="n-story-number">${String(i+1).padStart(2,'0')}</span><div><span class="n-label">${esc(s.category)} / ${date(s.date)}</span><h3>${esc(shortTitle(s))}</h3></div><span class="n-story-arrow">↗</span></a>`;
const error=(message)=>`<div class="n-error"><strong>We couldn't connect to Sleeper.</strong><p>${esc(message||'Scores will return when the connection is available.')}</p><button class="n-button" data-refresh>Try again ↻</button></div>`;
if(view==='index'){if(stories[0])$('homeLead').innerHTML=cover(stories[0]);$('homeStories').innerHTML=stories.slice(1,5).map(storyRow).join('')}
if(view==='news'){
 const lead=document.body.dataset.author?stories.find(s=>/anita|holly/i.test((s.author||'')+' '+s.title)):stories[0];if(lead&&$('newsLead'))$('newsLead').innerHTML=cover(lead);
 const bucket=s=>/sportsbook/i.test(s.category||'')?'Sportsbook':/anita|holly/i.test(s.author||s.title)?'Anita':/carl|scaries/i.test(s.category+' '+s.title)?'Carl':/recap/i.test(s.category)?'Recaps':/preview/i.test(s.category)?'Previews':'League';
 const cats=['All',...new Set(stories.map(bucket))];let selected=document.body.dataset.author||'All';
 $('newsFilters').innerHTML=cats.map(c=>`<button class="${c===selected?'selected':''}" data-category="${esc(c)}" aria-pressed="${c===selected}">${c}</button>`).join('');
 const render=()=>{const query=$('newsSearch').value.trim().toLowerCase();const list=stories.filter(s=>(selected==='All'||bucket(s)===selected)&&[s.title,s.subtitle,s.excerpt,s.author,s.category,(s.featuredOwners||[]).join(' ')].join(' ').toLowerCase().includes(query));$('newsCount').textContent=list.length+' STORIES';$('newsGrid').innerHTML=list.length?list.map((s,i)=>`<a class="n-news-card" href="${href(s)}"><div class="n-news-card-top"><span class="n-label">${esc(s.category)}</span><span>${date(s.date)}</span></div><h2>${esc(shortTitle(s))}</h2><p>${esc(s.excerpt)}</p><div class="n-news-card-bottom"><span>${esc(s.author||'CTE Network')}</span><b>↗</b></div></a>`).join(''):'<p class="n-empty">No stories match. Try another name or category.</p>'};
 $('newsFilters').onclick=e=>{const b=e.target.closest('button');if(!b)return;selected=b.dataset.category;for(const el of $('newsFilters').children){el.classList.toggle('selected',el===b);el.setAttribute('aria-pressed',String(el===b))}render()};$('newsSearch').oninput=render;render();return;
}
let snapshot,standingMode='overall';
function standings(rows,limit=12){
 const field=CTE_Quality.playoffField(snapshot.standings),seeds=new Map(field.map(r=>[r.ownerId,r]));
 const rec=x=>`${x.w}–${x.l}${x.t?'–'+x.t:''}`;
 return `<div class="n-table"><div class="n-table-head"><span>#</span><span>TEAM / OWNER</span><span>W–L–T</span><span>PF</span></div>${rows.slice(0,limit).map((r,i)=>{const seed=seeds.get(r.ownerId),split=snapshot.splits?.[r.ownerId];return `<a class="n-table-row " href="${CTE_UI.profileHref(r.ownerId)}"><span class="n-rank">${String(i+1).padStart(2,'0')}</span><span class="n-team-cell"><span class="n-avatar" aria-hidden="true">${esc(r.name.slice(0,2).toUpperCase())}</span><span><strong>${esc(r.name)}</strong><small>${esc(r.team)}</small>${view==='standings'?`<span class="n-team-status ${seed?'':'is-out'}">${seed?seed.bye?'Division leader · bye':seed.wildcard?'Wildcard position':'Division leader':'Outside playoff field'}</span>`:''}</span></span><span class="n-record">${r.wins}–${r.losses}${r.ties?'–'+r.ties:''}${view==='standings'?`<small class="n-record-breakdown">${split?`H2H ${rec(split.h2h)}<br>MED ${rec(split.median)}`:snapshot.splitState||'Loading splits…'}</small>`:''}</span><span class="n-points">${fmt(r.pf)}</span></a>`}).join('')}</div>`;
}
function renderPlayoffs(){
 const host=$('playoffField');if(!host||!snapshot)return;
 const field=CTE_Quality.playoffField(snapshot.standings);
 host.innerHTML=field.length?`<div class="n-playoff-grid">${field.map(r=>`<a class="n-playoff-slot ${r.bye?'is-bye':''}" href="${CTE_UI.profileHref(r.ownerId)}"><span class="n-label">SEED ${r.seed} / ${r.bye?'FIRST-ROUND BYE':r.wildcard?'WILDCARD':'DIVISION LEADER'}</span><strong>${esc(r.name)}</strong><small>${r.wins}–${r.losses}${r.ties?'–'+r.ties:''} · ${fmt(r.pf)} PF</small></a>`).join('')}</div><div class="n-playoff-cut n-playoff-note"><strong>Playoff cutoff</strong> · Next in line: ${snapshot.standings.filter(r=>!field.some(f=>f.ownerId===r.ownerId)).slice(0,2).map(r=>esc(r.name)).join(' · ')}</div><p class="n-playoff-note">If the season ended today: four division winners qualify, plus the best two remaining teams. The top two division winners receive first-round byes. Positions follow the live standings order; this is a current snapshot, not projected playoff odds or a clinching claim.</p>`:'<p class="n-playoff-note">The playoff field will appear once all four divisions are mapped.</p>';
}
async function loadSplits(snap,cfg){
 const targetSnapshot=snapshot;const last=Math.min(Math.max(0,snapshot.week-1),Number(snap.league.settings?.playoff_week_start||15)-1);
 if(!last){snapshot.splits={};snapshot.splitState='Season not started';renderStandings();return}
 try{const weeks=await Promise.all(Array.from({length:last},(_,i)=>CTE_Sleeper.getMatchups(cfg.sleeperLeagueId,i+1)));if(snapshot!==targetSnapshot)return;snapshot.splits=CTE_Quality.splitRecords(weeks,snapshot.lookup);snapshot.splitState=snapshot.splits?'':'Splits unavailable';if($('splitStamp'))$('splitStamp').textContent=snapshot.splits?`H2H and median records through Week ${last}; current-week results excluded.`:'Historical matchup records unavailable. Overall records still come from Sleeper.';renderStandings()}catch(_){if(snapshot!==targetSnapshot)return;snapshot.splitState='Splits unavailable';if($('splitStamp'))$('splitStamp').textContent='Historical matchup records unavailable. Overall records still come from Sleeper.';renderStandings()}
}
function renderStandings(){if(!snapshot)return;const rows=snapshot.standings;$('leagueStandings').innerHTML=standingMode==='overall'?standings(rows):['north','south','central','littleBabies'].map(d=>`<section class="n-division"><h2>${esc(CTE_UI.divisionName(d))}</h2>${standings(rows.filter(r=>r.division===d))}</section>`).join('')}
if(view==='standings')document.querySelectorAll('[data-standing]').forEach(b=>b.onclick=()=>{standingMode=b.dataset.standing;document.querySelectorAll('[data-standing]').forEach(el=>{el.classList.toggle('selected',el===b);el.setAttribute('aria-pressed',String(el===b))});renderStandings()});
function matchCard(pair,compact=false){const [a,b]=pair;const who=r=>{const m=snapshot.lookup[String(r.roster_id)];return {m,o:CTE_UI.owner(m?.ownerId)}};const aa=who(a),bb=who(b);const link=`matchup.html?season=${snapshot.season}&week=${snapshot.week}&matchup=${encodeURIComponent(a.matchup_id)}`;const sides=[[a,aa],[b,bb]];return `<a class="${compact?'n-score-tile':'n-match-card'}" href="${link}" data-owners="${esc(aa.m?.ownerId||'')},${esc(bb.m?.ownerId||'')}"><div class="n-match-meta"><span>WEEK ${snapshot.week}</span><span>${compact?'MATCHUP '+esc(a.matchup_id):'GAME '+String(a.matchup_id).padStart(2,'0')+' ↗'}</span></div>${sides.map(([r,{m,o}])=>`<div class="n-score-team"><span class="n-avatar" aria-hidden="true">${esc(o.name.slice(0,2).toUpperCase())}</span><span class="n-score-name"><strong>${esc(o.name)}</strong>${!compact?`<small>${esc(m?.sleeperTeamName||o.currentTeamName||'')}</small>`:''}</span><b class="n-score-value ${Number(r.points)>Number((r===a?b:a).points)?'n-leading':''}">${fmt(r.points)}</b></div>`).join('')}${!compact?`<div class="n-match-foot"><span>Current week totals</span><span>View matchup →</span></div>`:''}</a>`}
let loading=false;
async function load(){if(loading)return;loading=true;document.querySelectorAll('[data-refresh]').forEach(b=>b.disabled=true);try{const season=CTE_LEAGUE_DATA.league.currentSeason,cfg=CTE_LEAGUE_DATA.league.seasons[season],snap=await CTE_Sleeper.getLeagueSnapshot(cfg.sleeperLeagueId,{fresh:true});const lookup=CTE_UI.mapForSeason(season,snap.users,snap.rosters),week=Math.max(1,Number(snap.league?.settings?.leg||1));snapshot={...snap,season,lookup,week,standings:CTE_UI.standingsRows(snap.rosters,lookup)};
 if(view==='standings'){renderStandings();renderPlayoffs();loadSplits(snap,cfg);$('liveStamp').textContent='Updated '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
 if(view==='index'){$('homeStandings').innerHTML=standings(snapshot.standings,5);$('hubTitle').textContent='Week '+week+' · '+season;$('hubStatus').textContent='Scores, standings and this week’s sportsbook in one place.';}
 if(view==='index'||view==='game-day'){
 const target=view==='index'?'homeScores':'scoreboard';
 try{const rows=await CTE_Sleeper.getMatchups(cfg.sleeperLeagueId,week,{fresh:true}),groups=CTE_LeagueEngine.groupMatchups(rows).filter(p=>p.length===2);$(target).innerHTML=groups.length?groups.map(pair=>matchCard(pair,view==='index')).join(''):'<p class="n-empty">This week’s matchups haven’t been posted yet.</p>';try{document.dispatchEvent(new CustomEvent('cte:scoreboard',{detail:{view,season,week}}))}catch(_){};
 const stamp='Week '+week+' · Updated '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});if(view==='index')$('homeStamp').textContent=stamp+' · Sleeper';else{
 $('weekLabel').textContent=season+' / WEEK '+week;$('liveStamp').textContent=stamp;
 const high=[...rows].sort((a,b)=>Number(b.points)-Number(a.points))[0];const closest=groups.map(([a,b])=>Math.abs(Number(a.points||0)-Number(b.points||0))).sort((a,b)=>a-b)[0];const highName=high?CTE_UI.owner(lookup[String(high.roster_id)]?.ownerId).name:'—';$('gameStats').innerHTML=`<div><span class="n-label">WEEK HIGH</span><strong>${high?fmt(high.points):'—'}</strong><small>${esc(highName)}</small></div><div><span class="n-label">CLOSEST MARGIN</span><strong>${closest!=null?fmt(closest):'—'}</strong><small>Points between rivals</small></div><div><span class="n-label">MATCHUPS</span><strong>${groups.length}</strong><small>One league. All the drama.</small></div>`;
 const required=(snap.league.roster_positions||[]).filter(p=>!['BN','IR','TAXI'].includes(p)).length;$('readiness').innerHTML=rows.map(r=>{const o=CTE_UI.owner(lookup[String(r.roster_id)]?.ownerId),filled=(r.starters||[]).filter(id=>id&&id!=='0').length;return `<a href="${CTE_UI.profileHref(o.id)}" class="n-ready"><span>${esc(o.name)}</span><b class="${required&&filled>=required?'is-ready':''}">${required?filled+'/'+required:'Unknown'}</b></a>`}).join('');}
 }catch(e){$(target).innerHTML=error('Matchups are temporarily unavailable. Retry to reconnect.');if(view==='game-day')$('liveStamp').textContent='Matchup connection unavailable'}
 }
}catch(e){if(view==='index'){for(const id of ['homeScores','homeStandings'])$(id).innerHTML=error('Live data is unavailable. Stories and league navigation are still open.');$('homeStamp').textContent='Connection unavailable';if($('hubStatus'))$('hubStatus').textContent='Live scores are unavailable. Sportsbook and stories are still accessible.'}if(view==='game-day'){$('scoreboard').innerHTML=error();$('liveStamp').textContent='Connection unavailable'}if(view==='standings'){$('leagueStandings').innerHTML=error();$('liveStamp').textContent='Connection unavailable'}}finally{loading=false;document.querySelectorAll('[data-refresh]').forEach(b=>b.disabled=false)}}
document.addEventListener('click',e=>{if(e.target.closest('[data-refresh]'))load()});load();
})();
