const fs=require('fs'),path=require('path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');const output=path.resolve('review-v31');fs.mkdirSync(output,{recursive:true});
const server=require('http').createServer((req,res)=>{let file=path.join(root,decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file))}catch(e){res.statusCode=404;res.end('Not found')}});
const points=[142.34,136.18,108.52,126.72,99.84,117.26,129.88,118.04,114.28,123.60,137.22,132.74];
const rosters=points.map((_,i)=>({roster_id:i+1,owner_id:'owner'+i,settings:{wins:5-i%6,losses:i%6,ties:0,fpts:450-i*13,fpts_decimal:i*3},players:[],starters:Array(9).fill('123')}));
const users=rosters.map((r,i)=>({user_id:r.owner_id,display_name:'Owner '+i,metadata:{}}));
const matches=points.map((p,i)=>({roster_id:i+1,matchup_id:Math.floor(i/2)+1,points:p,starters:Array(9).fill('123'),players:[],players_points:{}}));
async function fixture(context){await context.route('https://api.sleeper.app/**',route=>{const u=new URL(route.request().url());let data=u.pathname.endsWith('/users')?users:u.pathname.endsWith('/rosters')?rosters:u.pathname.includes('/matchups/')?matches:u.pathname.includes('/transactions/')?[]:u.pathname.includes('/players/')?{}:u.pathname.endsWith('/drafts')?[{draft_id:'d1',season:'2026',settings:{teams:12}}]:u.pathname.includes('/draft/d1/picks')?Array.from({length:48},(_,i)=>({round:Math.floor(i/12)+1,pick_no:i+1,roster_id:i%12+1,metadata:{first_name:'Rookie',last_name:String(i+1),position:['QB','RB','WR','TE'][i%4],team:'FA'}})):{settings:{leg:3},roster_positions:['QB','RB','RB','WR','WR','TE','FLEX','FLEX','FLEX'],season:'2026'};return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)})});await context.route('https://sleepercdn.com/**',r=>r.abort())}
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));const b=await chromium.launch({headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const failures=[];const report=[];
for(const width of [360,390,1440]){const c=await b.newContext({viewport:{width,height:1040},deviceScaleFactor:1,serviceWorkers:'block',reducedMotion:'reduce'});await fixture(c);
for(const target of ['index.html','game-day.html','standings.html','news.html','article.html?id=2026-week-3-holly-sideline-debut','teams.html','carl.html','scores.html','schedule.html','rivalries.html','draft-central.html','team.html?owner=brendan','records.html','changes.html','sportsbook.html','article.html?id=2026-week-4-sportsbook-open','article.html?id=2026-week-4-bankroll-war','sportsbook.html#commissioner']){const p=await c.newPage();p.on('pageerror',e=>failures.push(`${width} ${target} JS: ${e.message}`));await p.goto('http://127.0.0.1:8765/'+target);await p.waitForTimeout(100);if(!await p.locator('main').isVisible())failures.push(target+': hidden main');let over=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);if(over)failures.push(`${width} ${target}: overflow`);
if(target==='index.html'){if(await p.locator('.n-score-tile').count()!==6)failures.push('Home matchups missing');await p.locator('.n-topbar .n-menu-button').click();if(!await p.locator('#networkMenu').evaluate(e=>e.open))failures.push('menu not open');await p.keyboard.press('Escape');if(await p.locator('#networkMenu').evaluate(e=>e.open))failures.push('menu not closed');if(!await p.locator('.n-topbar .n-menu-button').evaluate(e=>e===document.activeElement))failures.push('menu focus not restored');}
if(target==='standings.html'){if(await p.locator('#leagueStandings .n-table-row').count()!==12)failures.push('12 standings missing');await p.getByRole('button',{name:'By division'}).click();if(await p.locator('.n-division').count()!==4)failures.push('division toggle');await p.locator('[data-refresh]').first().click();await p.waitForTimeout(70);if(await p.locator('#leagueStandings .n-table-row').count()!==12)failures.push('standings refresh');await p.getByRole('button',{name:'Overall',exact:true}).click()}
if(target==='draft-central.html'&&await p.locator('.n-pick').count()!==48)failures.push('Draft board missing picks');
if(target==='game-day.html'&&await p.locator('.n-match-card').count()!==6)failures.push('Game Day missing matchups');
if(target==='news.html'){await p.locator('#newsSearch').fill('xyzNoMatches123');if(await p.locator('.n-news-card').count()!==0)failures.push('news search');await p.locator('#newsSearch').fill('');await p.locator('[data-category="Holly"]').click();if(await p.locator('.n-news-card').count()<1)failures.push('Holly filter');await p.locator('[data-category="All"]').click()}
if(width===390&&['index.html','game-day.html','standings.html','news.html'].includes(target)){await p.evaluate(()=>{document.querySelector('.n-edition').innerHTML='<span>DESIGN PREVIEW / SAMPLE SCORES</span><span>CTE / 29</span>';if(document.querySelector('#homeStamp'))document.querySelector('#homeStamp').textContent='Sample data for layout preview';if(document.querySelector('#liveStamp'))document.querySelector('#liveStamp').textContent='Sample data for layout preview'});await p.evaluate(()=>document.activeElement?.blur());await p.screenshot({path:`${output}/preview-${target.replace('.html','')}.png`,fullPage:false});}
if(width===1440&&target==='index.html'){await p.evaluate(()=>{document.activeElement?.blur();document.querySelector('.n-edition').innerHTML='<span>DESIGN PREVIEW / SAMPLE SCORES</span>';document.querySelector('#homeStamp').textContent='Sample data for layout preview'});await p.screenshot({path:path.join(output,'preview-desktop.png'),fullPage:false});}if(width===390&&['teams.html','carl.html','article.html?id=2026-week-3-holly-sideline-debut'].includes(target))await p.screenshot({path:output+'/qa-'+target.split('.')[0]+'.png',fullPage:true});report.push(`${width} ${target}: rendered`);await p.close()}
await c.close()}
// Failure state and retry without fake success.
const c=await b.newContext({viewport:{width:390,height:1040},serviceWorkers:'block'});await c.route('https://api.sleeper.app/**',r=>r.abort());const p=await c.newPage();await p.goto('http://127.0.0.1:8765/index.html');await p.waitForTimeout(100);if(await p.locator('#homeScores .n-error').count()!==1)failures.push('error state missing');if(await p.locator('#homeLead h2').count()!==1)failures.push('stories unavailable on API failure');await c.unroute('https://api.sleeper.app/**');await fixture(c);await p.locator('#homeScores [data-refresh]').click();await p.waitForTimeout(100);if(await p.locator('.n-score-tile').count()!==6)failures.push('retry failed');await c.close();
console.log(JSON.stringify({report,failures},null,2));fs.writeFileSync(path.join(output,'qa-v31.json'),JSON.stringify({report,failures},null,2));await b.close();server.close();if(failures.length)process.exitCode=1;
})();
